export const RESERVED_WORDS = [
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'implements',
  'import',
  'in',
  'instanceof',
  'interface',
  'let',
  'new',
  'null',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'super',
  'switch',
  'static',
  'this',
  'throw',
  'try',
  'true',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
  'constructor'
];

export const FUTURE_RESERVED_WORDS = [
  'await',
  'implements',
  'interface',
  'package',
  'private',
  'protected',
  'public'
];

export const STRICT_MODE_RESERVED_WORDS = [
  'implements',
  'interface',
  'let',
  'package',
  'private',
  'protected',
  'public',
  'static',
  'yield'
];

export const VUE_RESERVED_WORDS = [
  // Vue Instance Properties (Vue 2 and Vue 3)
  '$data',
  '$props',
  '$el',
  '$options',
  '$parent',
  '$root',
  '$children',
  '$refs',
  '$slots',
  '$scopedSlots',
  '$isServer',
  '$attrs',
  '$listeners',

  // Vue Instance Methods (Vue 2 and Vue 3)
  '$watch',
  '$set',
  '$delete',
  '$on',
  '$once',
  '$off',
  '$emit',
  '$mount',
  '$forceUpdate',
  '$nextTick',
  '$destroy',

  // Composition API (Vue 3 specific)
  'setup',
  'ref',
  'reactive',
  'readonly',
  'computed',
  'watchEffect',
  'onBeforeMount',
  'onMounted',
  'onBeforeUpdate',
  'onUpdated',
  'onBeforeUnmount',
  'onUnmounted',
  'onErrorCaptured',
  'onRenderTracked',
  'onRenderTriggered',
  'provide',
  'inject',

  // Component Options (Vue 2 and Vue 3)
  'data',
  'props',
  'propsData',
  'methods',
  'watch',
  'el',
  'template',
  'render',
  'renderError',
  'beforeCreate',
  'created',
  'beforeMount',
  'mounted',
  'beforeUpdate',
  'updated',
  'activated',
  'deactivated',
  'beforeDestroy',
  'destroyed',
  'errorCaptured',
  'directives',
  'filters',
  'components',
  'mixins',
  'extends',
  'provide',
  'inject',
  'beforeUnmount',
  'unmounted'
];

export const REACT_RESERVED_WORDS = [
  // React Component Lifecycle Methods
  'componentDidMount',
  'componentDidUpdate',
  'componentWillUnmount',
  'componentDidCatch',
  'getDerivedStateFromError',
  'getDerivedStateFromProps',
  'shouldComponentUpdate',
  'render',

  // React Component Properties
  'state',
  'props',
  'context',
  'refs',

  // React Specific Methods
  'setState',
  'forceUpdate',

  // React Hooks
  'useState',
  'useEffect',
  'useContext',
  'useReducer',
  'useCallback',
  'useMemo',
  'useRef',
  'useImperativeHandle',
  'useLayoutEffect',
  'useDebugValue',
  'useTransition',
  'useDeferredValue',
  'useId',

  // React Function Components
  'defaultProps',
  'displayName',
  'propTypes',
  'contextType',

  // JSX Reserved Words
  'children',
  'key',
  'ref',
  'dangerouslySetInnerHTML',

  // React DOM Properties and Methods
  'createElement',
  'cloneElement',
  'isValidElement',
  'Fragment',
  'StrictMode',
  'Suspense',
  'lazy',
  'memo',
  'forwardRef',
  'createContext',
  'createRef',
  'useContext',
  'useRef',
  'useReducer',
  'useCallback',
  'useMemo',
  'useLayoutEffect',
  'useDebugValue',

  // React PropTypes
  'array',
  'bool',
  'func',
  'number',
  'object',
  'string',
  'symbol',
  'node',
  'element',
  'elementType',
  'instanceOf',
  'oneOf',
  'oneOfType',
  'arrayOf',
  'objectOf',
  'shape',
  'exact'
];
